/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms.gui.dialog.au;

import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author Aldrin
 */
public class JDialogPurchaserAUD extends javax.swing.JDialog {

    private lms.gui.JFrameMainSLM mainMenu;
    private String evt = new String();
    private File pictureFile = null;
    private File photo;
    private lms.model.Purchaser purchaser = new lms.model.Purchaser();

    /**
     * Creates new form JDialogSupplierAUD
     */
    public JDialogPurchaserAUD(lms.gui.JFrameMainSLM parent, boolean modal) {
        super(parent, modal);
        this.mainMenu = parent;
        initComponents();
    }

    public JDialogPurchaserAUD(lms.gui.JFrameMainSLM parent, boolean modal, String evtl) {
        super(parent, modal);
        initComponents();
        this.evt = evtl;
        setTitle("Add Purchaser");
        jButtonSave.setText("Save");
        jButtonSave.setMnemonic('S');

    }

    public JDialogPurchaserAUD(lms.gui.JFrameMainSLM parent, boolean modal, String evtl, lms.model.Purchaser purchaser) {
        super(parent, modal);
        initComponents();
        this.evt = evtl;
        this.purchaser = purchaser;
        jButtonSave.setText("Update");
        jButtonSave.setMnemonic('U');
        jTextFieldFirstname.setText(this.purchaser.getFirstname());
        jTextFieldMiddlename.setText(this.purchaser.getMiddlename());
        jTextFieldLastname.setText(this.purchaser.getLastname());
        jTextFieldMobileNumber.setText(this.purchaser.getMobileNo());
        jTextAreaAddress.setText(this.purchaser.getAddress());
        jTextFieldEmail.setText(this.purchaser.getEmail());

    }

    public JDialogPurchaserAUD(lms.gui.JFrameMainSLM parent, boolean modal, lms.model.Purchaser purchaser, String evtl) {
        super(parent, modal);
        initComponents();
        this.evt = evtl;
        this.purchaser = this.purchaser;
        jButtonSave.setText("Delete");
        jButtonSave.setMnemonic('D');
        jTextFieldFirstname.setText(this.purchaser.getFirstname());
        jTextFieldMiddlename.setText(this.purchaser.getMiddlename());
        jTextFieldLastname.setText(this.purchaser.getLastname());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldFirstname = new javax.swing.JTextField();
        jTextFieldLastname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldMiddlename = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldMobileNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAddress = new javax.swing.JTextArea();
        jPanelButton = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel3.setText("Firstname");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 20, 180, -1));

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel4.setText("Lastname");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 180, -1));

        jTextFieldFirstname.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 230, -1));

        jTextFieldLastname.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, 230, -1));

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel5.setText("Middlename");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, -1));

        jTextFieldMiddlename.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldMiddlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 230, -1));

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel6.setText("Mobile No#");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, -1));

        jTextFieldMobileNumber.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldMobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 185, 230, -1));

        jLabel7.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel7.setText("Address");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 180, -1));

        jLabel8.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel8.setText("Email");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 180, -1));

        jTextFieldEmail.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 365, 230, -1));

        jTextAreaAddress.setColumns(20);
        jTextAreaAddress.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAddress);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 235, 230, 100));

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanelButton.setPreferredSize(new java.awt.Dimension(394, 60));
        jPanelButton.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(204, 204, 204)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSave.setMnemonic('S');
        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 100, 36));

        jPanelButton.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setPreferredSize(new java.awt.Dimension(10, 100));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanelButton.add(jPanel6, java.awt.BorderLayout.WEST);

        jPanel7.setPreferredSize(new java.awt.Dimension(10, 100));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanelButton.add(jPanel7, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanelButton, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(271, 511));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        try {
            switch (this.evt) {
                case "Add":
                    int reply = JOptionPane.showConfirmDialog(this,
                            "Are you sure  to save " + jTextFieldFirstname.getText() + "   " + jTextFieldLastname.getText() + " ?",
                            "Confirmation - Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
                    if (reply == JOptionPane.YES_OPTION) {
                        purchaser.setFirstname(jTextFieldFirstname.getText());
                        purchaser.setMiddlename(jTextFieldMiddlename.getText());
                        purchaser.setLastname(jTextFieldLastname.getText());
                        purchaser.setMobileNo(jTextFieldMobileNumber.getText());
                        purchaser.setAddress(jTextAreaAddress.getText());
                        purchaser.setEmail(jTextFieldEmail.getText());
                        new lms.util.QueryLMS().addPurchaser(purchaser);
                    } else if (reply == JOptionPane.NO_OPTION) {

                    }
                    this.dispose();
                    break;

                case "Update":
                    int upate = JOptionPane.showConfirmDialog(this,
                            "Are you sure  to save " + jTextFieldFirstname.getText() + "   " + jTextFieldLastname.getText() + " ?",
                            "Confirmation - Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
                    if (upate == JOptionPane.YES_OPTION) {
                        purchaser.setFirstname(jTextFieldFirstname.getText());
                        purchaser.setMiddlename(jTextFieldMiddlename.getText());
                        purchaser.setLastname(jTextFieldLastname.getText());
                        purchaser.setMobileNo(jTextFieldMobileNumber.getText());
                        purchaser.setAddress(jTextAreaAddress.getText());
                        purchaser.setEmail(jTextFieldEmail.getText());
                        new lms.util.QueryLMS().updatePurchaser(purchaser);
                    }
                    this.dispose();
                    break;
                case "Delete":
                    int response = JOptionPane.showConfirmDialog(null, "Are you sure to delete " + purchaser.getFirstname() + " " + purchaser.getLastname() + " ?", "Delete Confirmation!!", JOptionPane.YES_NO_OPTION);
                    if (response == JOptionPane.YES_OPTION) {
                        new lms.util.QueryLMS().deletePurchaser(purchaser);
                        JOptionPane.showMessageDialog(null, purchaser.getFirstname() + " " + purchaser.getLastname() + " is successfully deleted.", "Message", JOptionPane.PLAIN_MESSAGE);
                    }
                    this.dispose();
                    break;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSave;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaAddress;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFirstname;
    private javax.swing.JTextField jTextFieldLastname;
    private javax.swing.JTextField jTextFieldMiddlename;
    private javax.swing.JTextField jTextFieldMobileNumber;
    // End of variables declaration//GEN-END:variables

}
