/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms.gui.dialog.au;

import java.io.File;
import javax.swing.JOptionPane;
import lms.util.QueryLMS;

/**
 *
 * @author Aldrin
 */
public class JDialogCallNumberLineAUD extends javax.swing.JDialog {

    private lms.gui.JFrameMainSLM mainMenu;
    private String evt = new String();
    private File pictureFile = null;
    private File photo;
    private lms.model.CallNumberLine1 callNumberLine1 = new lms.model.CallNumberLine1();

    /**
     * Creates new form JDialogSupplierAUD
     */
    public JDialogCallNumberLineAUD(lms.gui.JFrameMainSLM parent, boolean modal) {
        super(parent, modal);
        this.mainMenu = parent;
        initComponents();
    }

    public JDialogCallNumberLineAUD(lms.gui.JFrameMainSLM parent, boolean modal, String evtl) {
        super(parent, modal);
        initComponents();
        this.evt = evtl;
        setTitle("Add Call Number");
        jButtonSave.setText("Save");
        jButtonSave.setMnemonic('S');

    }

    public JDialogCallNumberLineAUD(lms.gui.JFrameMainSLM parent, boolean modal, String evtl, lms.model.CallNumberLine1 category) {
        super(parent, modal);
        initComponents();
        this.evt = evtl;
        this.callNumberLine1 = category;
        jButtonSave.setText("Update");
        jButtonSave.setMnemonic('U');
        jTextFieldLetter.setText(this.callNumberLine1.getLetters());
        jTextAreaDescription.setText(this.callNumberLine1.getDescription());

    }

    public JDialogCallNumberLineAUD(lms.gui.JFrameMainSLM parent, boolean modal, lms.model.CallNumberLine1 unit, String evtl) {
        super(parent, modal);
        initComponents();
        this.evt = evtl;
        this.callNumberLine1 = unit;
        jButtonSave.setText("Delete");
        jButtonSave.setMnemonic('D');
        jTextFieldLetter.setText(unit.getLetters());
        jTextAreaDescription.setText(unit.getDescription());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldLetter = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jPanelButton = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Call Number Line 1");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel3.setText("Letter");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 20, 180, -1));

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel4.setText("Description");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, -1));

        jTextFieldLetter.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldLetter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 290, -1));

        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescription);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 290, 60));

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanelButton.setPreferredSize(new java.awt.Dimension(394, 60));
        jPanelButton.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(204, 204, 204)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSave.setMnemonic('S');
        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 100, 36));

        jPanelButton.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setPreferredSize(new java.awt.Dimension(10, 100));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanelButton.add(jPanel6, java.awt.BorderLayout.WEST);

        jPanel7.setPreferredSize(new java.awt.Dimension(10, 100));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanelButton.add(jPanel7, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanelButton, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(331, 270));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        if ((jTextFieldLetter.getText().isEmpty()) || (jTextAreaDescription.getText().isEmpty())) {
            JOptionPane.showMessageDialog(mainMenu, "Empty fields is not allowed.", "Please try again!!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            switch (this.evt) {
                case "Add":
                    int reply = JOptionPane.showConfirmDialog(this,
                            "Are you sure  to save " + jTextFieldLetter.getText() + "   " + jTextAreaDescription.getText() + " ?",
                            "Confirmation - Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
                    if (reply == JOptionPane.YES_OPTION) {
                        callNumberLine1.setLetters(jTextFieldLetter.getText());
                        callNumberLine1.setDescription(jTextAreaDescription.getText());
                        new QueryLMS().addCallNumberLine1(callNumberLine1);
                    } else if (reply == JOptionPane.NO_OPTION) {

                    }
                    this.dispose();
                    break;

                case "Update":
                    int upate = JOptionPane.showConfirmDialog(this,
                            "Are you sure  to save " + jTextFieldLetter.getText() + "   " + jTextAreaDescription.getText() + " ?",
                            "Confirmation - Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
                    if (upate == JOptionPane.YES_OPTION) {
                        callNumberLine1.setLetters(jTextFieldLetter.getText());
                        callNumberLine1.setDescription(jTextAreaDescription.getText());
                        new QueryLMS().updateCallNumberLine1(callNumberLine1);
                    }
                    this.dispose();
                    break;
                case "Delete":
                    int response = JOptionPane.showConfirmDialog(null, "Are you sure to delete " + callNumberLine1.getLetters() + " " + callNumberLine1.getDescription() + " ?", "Delete Confirmation!!", JOptionPane.YES_NO_OPTION);
                    if (response == JOptionPane.YES_OPTION) {
                        new QueryLMS().deleteCallNumberLine1(callNumberLine1);
                        JOptionPane.showMessageDialog(null, callNumberLine1.getLetters() + " " + callNumberLine1.getDescription() + " is successfully deleted.", "Message", JOptionPane.PLAIN_MESSAGE);
                    }
                    this.dispose();
                    break;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSave;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextField jTextFieldLetter;
    // End of variables declaration//GEN-END:variables

}
