/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms.gui.dialog.au;

import java.io.File;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import lms.model.Penalty;
import lms.util.QueryLMS;

/**
 *
 * @author Aldrin
 */
public class JDialogPenaltyAUD extends javax.swing.JDialog {

    private lms.gui.JFrameMainSLM mainMenu;
    private String evt = new String();
    private File pictureFile = null;
    private File photo;
    private Penalty penalty = new Penalty();
    private QueryLMS query = new QueryLMS();
    private DecimalFormat df = new DecimalFormat("##,##0.00");

    /**
     * Creates new form JDialogSupplierAUD
     */
    public JDialogPenaltyAUD(lms.gui.JFrameMainSLM parent, boolean modal) {
        super(parent, modal);
        this.mainMenu = parent;
        initComponents();
        days();
    }

    public JDialogPenaltyAUD(lms.gui.JFrameMainSLM parent, boolean modal, String evtl) {
        super(parent, modal);
        initComponents();
        this.evt = evtl;
        setTitle("Add Penalty");
        jButtonSave.setText("Save");
        jButtonSave.setMnemonic('S');
        days();

    }

    public JDialogPenaltyAUD(lms.gui.JFrameMainSLM parent, boolean modal, String evtl, lms.model.Penalty penalty) {
        super(parent, modal);
        initComponents();
        this.evt = evtl;
        this.penalty = penalty;
        jButtonSave.setText("Update");
        jButtonSave.setMnemonic('U');
        jTextFieldRate.setText(df.format(penalty.getRate()));
        jCheckBoxActive.setSelected(penalty.getActive()); 
        days();
        jComboBox1.setSelectedIndex(penalty.getDaysToBorrow()-1);


    }

    public JDialogPenaltyAUD(lms.gui.JFrameMainSLM parent, boolean modal, lms.model.Penalty penalty, String evtl) {
        super(parent, modal);
        initComponents();
        this.evt = evtl;
//        this.penalty = penalty;
        jButtonSave.setText("Delete");
        jButtonSave.setMnemonic('D');
        jTextFieldRate.setText(String.valueOf(penalty.getRate()));
        jCheckBoxActive.setSelected(penalty.getActive());
        days();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldRate = new javax.swing.JTextField();
        jCheckBoxActive = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanelButton = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldRate.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 260, -1));

        jCheckBoxActive.setText("Active");
        jPanel2.add(jCheckBoxActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 260, -1));

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel4.setText("Rate");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 20, 260, -1));

        jComboBox1.setPreferredSize(new java.awt.Dimension(56, 23));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 260, -1));

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel5.setText("Days to borrow books");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 260, -1));

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanelButton.setPreferredSize(new java.awt.Dimension(394, 60));
        jPanelButton.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(204, 204, 204)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSave.setMnemonic('S');
        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 100, 36));

        jPanelButton.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setPreferredSize(new java.awt.Dimension(10, 100));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanelButton.add(jPanel6, java.awt.BorderLayout.WEST);

        jPanel7.setPreferredSize(new java.awt.Dimension(10, 100));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanelButton.add(jPanel7, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanelButton, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(299, 250));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        try {
            switch (this.evt) {
                case "Add":
                    int reply = JOptionPane.showConfirmDialog(mainMenu,
                            "Are you sure  to save " + jTextFieldRate.getText() + " ?",
                            "Confirmation - Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
                    if (reply == JOptionPane.YES_OPTION) {
                        if(jCheckBoxActive.isSelected() ==true){
                            query.updateActiveAllPenalty();
                        }
                        penalty.setRate(Float.parseFloat(jTextFieldRate.getText()));
                        penalty.setActive(jCheckBoxActive.isSelected());
                        penalty.setDaysToBorrow(Integer.parseInt(jComboBox1.getSelectedItem().toString()));
                        new QueryLMS().addPenalty(penalty);
                        JOptionPane.showMessageDialog(mainMenu, "New penalty rate is recorded!", "Message", JOptionPane.PLAIN_MESSAGE);
                    } else if (reply == JOptionPane.NO_OPTION) {

                    }
                    this.dispose();
                    break;

                case "Update":
                    int upate= JOptionPane.showConfirmDialog(mainMenu,
                            "Are you sure  to save " + jTextFieldRate.getText() +" ?",
                            "Confirmation - Exit", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
                    if (upate == JOptionPane.YES_OPTION) {
                        if(jCheckBoxActive.isSelected() ==true){
                            query.updateActiveAllPenalty();
                            query.updatedActiveOnePenalty(penalty);
                        }
                        penalty.setRate(Float.parseFloat(jTextFieldRate.getText()));
                        penalty.setActive(jCheckBoxActive.isSelected());
                        penalty.setDaysToBorrow(Integer.parseInt(jComboBox1.getSelectedItem().toString()));
                        query.updatePenalty(penalty);
                    }
                    this.dispose();
                    break;
                case "Delete":
                    int response = JOptionPane.showConfirmDialog(mainMenu, "Are you sure to delete the penalty?", "Delete Confirmation!!", JOptionPane.YES_NO_OPTION);
                    if (response == JOptionPane.YES_OPTION) {
                        new QueryLMS().deletePenalty(penalty);
                        JOptionPane.showMessageDialog(mainMenu, "Penalty is successfully deleted.", "Message", JOptionPane.PLAIN_MESSAGE);
                    }
                    this.dispose();
                    break;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSave;
    private javax.swing.JCheckBox jCheckBoxActive;
    private javax.swing.JComboBox<Integer> jComboBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelButton;
    private javax.swing.JTextField jTextFieldRate;
    // End of variables declaration//GEN-END:variables

    
    public void days(){
        int days=366;
        for(int i =1;i<days;i++){
            jComboBox1.addItem(i);
        }
    }
}
