/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms.gui;

import java.awt.AlphaComposite;
import java.awt.Graphics2D;
import lms.gui.dialog.JDialogReceivePenaltyPayments;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.beans.PropertyVetoException;
import java.sql.Blob;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import lms.gui.dialog.JDialogBook;
import lms.gui.dialog.JDialogAuthor;
import lms.gui.dialog.JDialogTypes;
import lms.gui.dialog.JDialogPublisher;
import lms.events.SLMActionListener;
import lms.gui.dialog.JDialogCallNumberLine1;
import lms.gui.dialog.JDialogChangePassword;
import lms.gui.dialog.JDialogCourse;
import lms.gui.dialog.JDialogFaculty;
import lms.gui.dialog.JDialogLogin;
import lms.gui.dialog.JDialogPenalty;
import lms.gui.dialog.JDialogPurchaser;
import lms.gui.dialog.JDialogStudent;
import lms.gui.dialog.JDialogUser;
import lms.gui.dialog.JDialogViewRecievedBooks;
import lms.model.User;
import lms.reports.JDialogBookInventory;
import lms.reports.JDialogPenaltyListReport;
import lms.util.LoginUser;

/**
 *
 * @author admin
 */
public class JFrameMainSLM extends javax.swing.JFrame {
    
    private lms.gui.internalframe.JInternalFrameBooksList internalFrameBooks = new lms.gui.internalframe.JInternalFrameBooksList("Book List", true, true, true, true, this);
    private lms.gui.internalframe.JInternalFrameBorrowedBooks internalFrameBorrowedBooks = new lms.gui.internalframe.JInternalFrameBorrowedBooks("Borrowed Books", true, true, true, true, this);
    private lms.gui.internalframe.JInternalFrameStudentPenalty internalFrameStudentPenalty = new lms.gui.internalframe.JInternalFrameStudentPenalty("Student Penalty", true, true, true, true, this);
    private lms.model.User user = new User();
    private lms.util.QueryLMS query = new lms.util.QueryLMS();
    int IMG_WIDTH = 16;
    int IMG_HEIGHT = 16;

    /**
     * Creates new form JFrameMainSLM
     */
    public JFrameMainSLM() {
        Image icon = Toolkit.getDefaultToolkit().getImage(System.getProperty("user.dir") + "/src/lms/images/no photo.jpg");
        setIconImage(icon);
        initComponents();
//        setTitle("Library Management System [LMS]");
        jMenuItemExit.addActionListener(new SLMActionListener());
//        jMenuLMS.setText(new LoginUser().getUser().getFirstname() + "  " + new LoginUser().getUser().getMiddlename() + "   " + new LoginUser().getUser().getLastname());
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        if (!internalFrameBorrowedBooks.isVisible()) {
            jDesktopPane1.add(internalFrameBorrowedBooks);
            try {
                internalFrameBorrowedBooks.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(JFrameMainSLM.class.getName()).log(Level.SEVERE, null, ex);
            }
            internalFrameBorrowedBooks.setVisible(true);
        }
        internalFrameBorrowedBooks.toFront();
        internalFrameBorrowedBooks.setFocusable(true);
        logIn();
        displayUserPhoto();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelNorth = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanelCenter = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuLMS = new javax.swing.JMenu();
        jMenuItemLogin = new javax.swing.JMenuItem();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenuItemChangePassword = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuSettings = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuBorrow = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuReport = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanelNorth.setPreferredSize(new java.awt.Dimension(1348, 45));
        jPanelNorth.setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        jButton2.setText("<html><center>Borrowed<br><p style=\" color: red;padding-top: 0px;\">Books</p></center></html>");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMaximumSize(new java.awt.Dimension(73, 43));
        jButton2.setMinimumSize(new java.awt.Dimension(73, 43));
        jButton2.setPreferredSize(new java.awt.Dimension(43, 43));
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton1.setText("<html><center>Manage<br><p style=\" color: red;padding-top: 0px;\">Books</p></center></html>");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMaximumSize(new java.awt.Dimension(73, 43));
        jButton1.setMinimumSize(new java.awt.Dimension(73, 43));
        jButton1.setPreferredSize(new java.awt.Dimension(63, 43));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton3.setText("<html><center>Student<br><p style=\" color: red;padding-top: 0px;\">Penalty</p></center></html>");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMaximumSize(new java.awt.Dimension(73, 43));
        jButton3.setMinimumSize(new java.awt.Dimension(73, 43));
        jButton3.setPreferredSize(new java.awt.Dimension(43, 43));
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setText("<html><center>Penalty<br><p style=\" color: red;padding-top: 0px;\">Payment</p></center></html>");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setMaximumSize(new java.awt.Dimension(73, 43));
        jButton4.setMinimumSize(new java.awt.Dimension(73, 43));
        jButton4.setPreferredSize(new java.awt.Dimension(43, 43));
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jPanelNorth.add(jToolBar1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanelNorth, java.awt.BorderLayout.NORTH);

        jPanelCenter.setBackground(new java.awt.Color(153, 153, 153));
        jPanelCenter.setLayout(new java.awt.BorderLayout());

        jDesktopPane1.setBackground(new java.awt.Color(153, 153, 153));
        jDesktopPane1.setOpaque(false);
        jDesktopPane1.setLayout(new java.awt.BorderLayout());
        jPanelCenter.add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanelCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuLMS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/changepassword16.png"))); // NOI18N
        jMenuLMS.setText("LMS");
        jMenuLMS.setFocusable(false);

        jMenuItemLogin.setText("Login");
        jMenuItemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginActionPerformed(evt);
            }
        });
        jMenuLMS.add(jMenuItemLogin);

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuLMS.add(jMenuItemLogout);

        jMenuItemChangePassword.setText("Change Password");
        jMenuItemChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemChangePasswordActionPerformed(evt);
            }
        });
        jMenuLMS.add(jMenuItemChangePassword);
        jMenuLMS.add(jSeparator1);

        jMenuItemExit.setText("Exit");
        jMenuLMS.add(jMenuItemExit);

        jMenuBar1.add(jMenuLMS);

        jMenuSettings.setText("Administration");
        jMenuSettings.setFocusable(false);

        jMenu3.setText("Books");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Author");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Publisher");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem1.setText("Type");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem4.setText("Genre");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem12.setText("Call Number");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuSettings.add(jMenu3);

        jMenuItem5.setText("User");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuSettings.add(jMenuItem5);

        jMenuItem13.setText("Purchaser");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenuSettings.add(jMenuItem13);

        jMenuItem14.setText("Course");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenuSettings.add(jMenuItem14);

        jMenuItem6.setText("Student");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenuSettings.add(jMenuItem6);

        jMenuItem15.setText("Penalty");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenuSettings.add(jMenuItem15);

        jMenuItem16.setText("Faculty");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenuSettings.add(jMenuItem16);

        jMenuBar1.add(jMenuSettings);

        jMenuBorrow.setText("View");
        jMenuBorrow.setFocusable(false);

        jMenuItem8.setText("Books Recieved");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenuBorrow.add(jMenuItem8);

        jMenuItem7.setText("Borrowed Books");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenuBorrow.add(jMenuItem7);

        jMenuItem11.setText("Penalty");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenuBorrow.add(jMenuItem11);

        jMenuBar1.add(jMenuBorrow);

        jMenuReport.setText("Reports");
        jMenuReport.setFocusable(false);

        jMenuItem17.setText("Student Penalty");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenuReport.add(jMenuItem17);

        jMenuItem18.setText("BookList");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenuReport.add(jMenuItem18);

        jMenuBar1.add(jMenuReport);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1350, 796));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JDialogTypes category = new JDialogTypes(this, true);
        category.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        JDialogBook books = new JDialogBook(this, true);
        books.setVisible(true);
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
//        JDialogBook books = new JDialogBook(this, true);
//        books.setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JDialogAuthor dialogAuthor = new JDialogAuthor(this, true);
        dialogAuthor.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JDialogPublisher publisher = new JDialogPublisher(this, true);
        publisher.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        lms.gui.dialog.JDialogGenre genre = new lms.gui.dialog.JDialogGenre(this, true);
        genre.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginActionPerformed
        JDialogLogin logIn = new JDialogLogin(this, true);
        logIn.setVisible(true);
        logIn();
    }//GEN-LAST:event_jMenuItemLoginActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        JDialogCallNumberLine1 callNumberLine1 = new JDialogCallNumberLine1(this, true);
        callNumberLine1.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!internalFrameBooks.isVisible()) {
            jDesktopPane1.add(internalFrameBooks);
            try {
                internalFrameBooks.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(JFrameMainSLM.class.getName()).log(Level.SEVERE, null, ex);
            }
            internalFrameBooks.setVisible(true);
            
        }
        internalFrameBooks.toFront();
        internalFrameBooks.setFocusable(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if (!internalFrameBorrowedBooks.isVisible()) {
            jDesktopPane1.add(internalFrameBorrowedBooks);
            try {
                internalFrameBorrowedBooks.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(JFrameMainSLM.class.getName()).log(Level.SEVERE, null, ex);
            }
            internalFrameBorrowedBooks.setVisible(true);
        }
        internalFrameBorrowedBooks.toFront();
        internalFrameBorrowedBooks.setFocusable(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        JDialogPurchaser purchaser = new JDialogPurchaser(this, true);
        purchaser.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        JDialogCourse course = new JDialogCourse(this, true);
        course.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        JDialogStudent student = new JDialogStudent(this, true);
        student.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        JDialogPenalty penalty = new JDialogPenalty(this, true);
        penalty.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        if (!internalFrameStudentPenalty.isVisible()) {
            jDesktopPane1.add(internalFrameStudentPenalty);
            try {
                internalFrameStudentPenalty.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(JFrameMainSLM.class.getName()).log(Level.SEVERE, null, ex);
            }
            internalFrameStudentPenalty.setVisible(true);
        }
        internalFrameStudentPenalty.toFront();
        internalFrameStudentPenalty.setFocusable(true);
        internalFrameStudentPenalty.selectStudentBookBorrewed();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        JDialogFaculty faculty = new JDialogFaculty(this, true);
        faculty.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        JDialogPenaltyListReport report = new JDialogPenaltyListReport(this, true);
        report.setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        if (!internalFrameBorrowedBooks.isVisible()) {
            jDesktopPane1.add(internalFrameBorrowedBooks);
            try {
                internalFrameBorrowedBooks.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(JFrameMainSLM.class.getName()).log(Level.SEVERE, null, ex);
            }
            internalFrameBorrowedBooks.setVisible(true);
        }
        internalFrameBorrowedBooks.toFront();
        internalFrameBorrowedBooks.setFocusable(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        if (!internalFrameStudentPenalty.isVisible()) {
            jDesktopPane1.add(internalFrameStudentPenalty);
            try {
                internalFrameStudentPenalty.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(JFrameMainSLM.class.getName()).log(Level.SEVERE, null, ex);
            }
            internalFrameStudentPenalty.setVisible(true);
        }
        internalFrameStudentPenalty.toFront();
        internalFrameStudentPenalty.setFocusable(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JDialogUser user = new JDialogUser(this, true);
        user.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItemChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemChangePasswordActionPerformed
        JDialogChangePassword change = new JDialogChangePassword(this, true);
        change.setVisible(true);
    }//GEN-LAST:event_jMenuItemChangePasswordActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Are you sure to logout?", "CONFIRM LOGOUT!!", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION) {
            logOut();
        }
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JDialogReceivePenaltyPayments penaltyPayment = new JDialogReceivePenaltyPayments(this, true);
        penaltyPayment.setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        JDialogBookInventory bookInventory = new JDialogBookInventory(this, true);
        bookInventory.setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        JDialogViewRecievedBooks vrbooks = new JDialogViewRecievedBooks(this, true);
        vrbooks.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBorrow;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItemChangePassword;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemLogin;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenu jMenuLMS;
    private javax.swing.JMenu jMenuReport;
    private javax.swing.JMenu jMenuSettings;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelNorth;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    private void logOut() {
        new LoginUser().setUser(null);
        jDesktopPane1.setVisible(false);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jMenuItemLogout.setVisible(false);
        jMenuItemLogin.setVisible(true);
        jMenuItemChangePassword.setVisible(false);
        jMenuBorrow.setEnabled(false);
        jMenuSettings.setEnabled(false);
        jMenuReport.setEnabled(false);
        jMenuLMS.setText("Library Management System [LMS v.1.0.1]");
        jMenuLMS.setIcon(null);
        
    }
    
    private void logIn() {
        
        jMenuLMS.setText(new LoginUser().getUser().getFirstname() + "  " + new LoginUser().getUser().getMiddlename() + "  " + new LoginUser().getUser().getLastname());
//        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setTitle("Library Management System [LMS v.1.0.1]");
        jDesktopPane1.setVisible(true);
        jMenuItemLogout.setVisible(true);
        jMenuItemLogin.setVisible(false);
        jMenuItemChangePassword.setVisible(true);
        jMenuBorrow.setEnabled(true);
        jMenuSettings.setEnabled(true);
        jMenuReport.setEnabled(true);
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        displayUserPhoto();
        
    }
    
    private void displayUserPhoto() {
        try {
            Blob blobImage = (Blob) query.selectedUserPicture(new LoginUser().getUser());
            ImageIcon icon = new ImageIcon(blobImage.getBytes(1L, (int) blobImage.length()));
            Image image = icon.getImage();
            int type = BufferedImage.TYPE_INT_ARGB;
            
            BufferedImage resizedImage = new BufferedImage(IMG_WIDTH, IMG_HEIGHT, type);
            Graphics2D g = resizedImage.createGraphics();
            g.drawImage(image, 0, 0, IMG_WIDTH, IMG_HEIGHT, null);
            g.dispose();
            g.setComposite(AlphaComposite.Src);
            
            g.setRenderingHint(RenderingHints.KEY_INTERPOLATION,
                    RenderingHints.VALUE_INTERPOLATION_BILINEAR);
            g.setRenderingHint(RenderingHints.KEY_RENDERING,
                    RenderingHints.VALUE_RENDER_QUALITY);
            g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                    RenderingHints.VALUE_ANTIALIAS_ON);
            jMenuLMS.setIcon(new ImageIcon(resizedImage));
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
}
