/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms.gui.dialog;

import java.awt.Dimension;
import java.awt.Font;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import lms.gui.JFrameMainSLM;
import lms.model.Student;
import lms.util.QueryLMS;

/**
 *
 * @author admin
 */
public class JDialogStudentPenaltiesDetails extends javax.swing.JDialog {

    private QueryLMS query = new QueryLMS();
    private JFrameMainSLM mainFrame;
    private Student student = new Student();

    /**
     * Creates new form JDialogStudentPenaltiesDetails
     */
    public JDialogStudentPenaltiesDetails(lms.gui.JFrameMainSLM parent, boolean modal, lms.model.Student student, String studentName) {
        super(parent, modal);
        this.mainFrame = parent;
        this.student = student;
        initComponents();
        setTable();
        selectStudentPenaltyDetails();
        jLabelStudent.setText(studentName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelStudent = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student Borrowed Details");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel1.setText("Student");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 30));

        jLabelStudent.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        getContentPane().add(jLabelStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 259, 31));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 940, 440));

        setSize(new java.awt.Dimension(977, 545));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelStudent;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
   //table 2
    public DefaultTableModel tableModel2 = new DefaultTableModel() {
        public Class getColumnClass(int columnIndex) {
            if (columnIndex == 0) {
                return String.class;
            }
            switch (columnIndex) {
                case 1:
                    return String.class;
                case 2:
                    return String.class;
                case 3:
                    return String.class;
                case 4:
                    return Integer.class;
                case 5:
                    return Integer.class;
                case 6:
                    return Integer.class;
                default:
                    return String.class;
            }
        }

        public boolean isCellEditable(int row, int col) {
            if (col < 10) {
                return false;

            } else {
                return true;
            }
        }
    };
    private TableRowSorter<TableModel> sorter2 = new TableRowSorter<TableModel>(tableModel2);

    public void setTable() {
        try {
//            v.add(idl);
//                v.add(titlel);
//                v.add(borrowedDatel);
//                v.add(returnDatel);
//                v.add(daysl);
//                v.add(ratel);
//                v.add(penaltyAmountl);
            String[] columnNames = {
                "Book Borrowed Id",//
                "Title",//1
                "Borrowed Date",//2
                "Returned Date",//3
                "Days",//4
                "Rate",//5
                "Penalty",//6
            };//15

            jTable1 = new javax.swing.JTable(tableModel2);
            JTableHeader header = jTable1.getTableHeader();
            header.setPreferredSize(new Dimension(100, 35));
            header.setFont(new Font("Courier New", Font.PLAIN, 14));
            header.setBackground(new java.awt.Color(153, 153, 153));
            jTable1.setRowSorter(sorter2);
            jTable1.setRowHeight(30);
            jTable1.setFont(new Font("Courier New", Font.PLAIN, 14));
//            jTable1.setCellSelectionEnabled(true);
            jTable1.setFocusable(false);
            for (int i = 0; i < columnNames.length;) {
                tableModel2.addColumn(columnNames[i]);
                i++;
            }

            jScrollPane1.setViewportView(jTable1);

            TableColumn[] column = new TableColumn[100];

            column[0] = jTable1.getColumnModel().getColumn(0);
            column[0].setPreferredWidth(40);

            column[1] = jTable1.getColumnModel().getColumn(1);
            column[1].setPreferredWidth(250);

            column[2] = jTable1.getColumnModel().getColumn(2);
            column[2].setPreferredWidth(200);

            column[3] = jTable1.getColumnModel().getColumn(3);
            column[3].setPreferredWidth(200);

            column[4] = jTable1.getColumnModel().getColumn(4);
            column[4].setPreferredWidth(60);
            
            column[5] = jTable1.getColumnModel().getColumn(5);
            column[5].setPreferredWidth(60);

            column[6] = jTable1.getColumnModel().getColumn(6);
            column[6].setPreferredWidth(60);

            

            TableColumn hidden1 = jTable1.getColumnModel().getColumn(0);
            hidden1.setMinWidth(0);
            hidden1.setPreferredWidth(0);
            hidden1.setMaxWidth(0);
//            TableColumn hidden2 = jTable2.getColumnModel().getColumn(1);
//            hidden2.setMinWidth(0);
//            hidden2.setPreferredWidth(0);
//            hidden2.setMaxWidth(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void selectStudentPenaltyDetails() {
        tableModel2.setRowCount(0);
        query.selectStudentPenalyDetails(student.getId());
        for (int i = 0; i < query.getData().size(); i++) {
            tableModel2.addRow((Vector) query.getData().get(i));
        }
    }

}
