/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms.gui.internalframe;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import lms.gui.JFrameMainSLM;
import lms.gui.dialog.JDialogAddBookPhoto;
import lms.gui.dialog.JDialogEditBooks;
import lms.model.Book;
import lms.model.CallNumberLine1;
import lms.model.Genre;
import lms.model.Publisher;
import lms.util.QueryLMS;

/**
 *
 * @author Aldrin
 */
public class JInternalFrameBooksList extends javax.swing.JInternalFrame implements MouseListener {

    private JFrameMainSLM mainFrame;
    private Book book = new Book();
    private Publisher publisher = new Publisher();
    private CallNumberLine1 callNoLine1 = new CallNumberLine1();
    private Genre genre = new Genre();

    /**
     * Creates new form JInternalFrameBooksList
     */
    public JInternalFrameBooksList() {
        initComponents();
    }

    public JInternalFrameBooksList(String title, boolean resizable, boolean closable, boolean maximizable, boolean iconifiable, JFrameMainSLM mainFrame) {

        setRootPane(createRootPane());
        setLayout(new BorderLayout());
        this.title = title;
        this.resizable = resizable;
        this.closable = closable;
        this.maximizable = maximizable;
        isMaximum = false;
        this.iconable = iconifiable;
        isIcon = false;
        setRootPaneCheckingEnabled(true);
        desktopIcon = new JDesktopIcon(this);
        updateUI();
        sun.awt.SunToolkit.checkAndSetPolicy(this);
        this.mainFrame = mainFrame;
        initComponents();
        setTable();
        jButtonEditBook.setEnabled(false);
        jButtonAddPhoto.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonEditBook = new javax.swing.JButton();
        jButtonAddPhoto = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBook = new javax.swing.JTable();

        setMaximizable(true);
        setTitle("Books List");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel2.setPreferredSize(new java.awt.Dimension(1308, 40));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("   Books Information");
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(748, 45));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setPreferredSize(new java.awt.Dimension(450, 100));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Search");
        jPanel5.add(jLabel2);

        jTextFieldSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldSearch.setPreferredSize(new java.awt.Dimension(200, 30));
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyReleased(evt);
            }
        });
        jPanel5.add(jTextFieldSearch);

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setPreferredSize(new java.awt.Dimension(650, 72));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jButtonAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAdd.setMnemonic('A');
        jButtonAdd.setText("Add New");
        jButtonAdd.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonAdd);

        jButtonEditBook.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonEditBook.setMnemonic('D');
        jButtonEditBook.setText("Edit Book");
        jButtonEditBook.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonEditBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditBookActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonEditBook);

        jButtonAddPhoto.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonAddPhoto.setMnemonic('D');
        jButtonAddPhoto.setText("Change Photo");
        jButtonAddPhoto.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonAddPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPhotoActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonAddPhoto);

        jPanel4.add(jPanel6, java.awt.BorderLayout.WEST);

        jPanel3.add(jPanel4, java.awt.BorderLayout.NORTH);

        jTableBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableBook);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyReleased
        String text = jTextFieldSearch.getText().trim();
        if (text.length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text + ",*"));
        }
    }//GEN-LAST:event_jTextFieldSearchKeyReleased

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        lms.gui.dialog.JDialogRecievedNewBooks u = new lms.gui.dialog.JDialogRecievedNewBooks(mainFrame, true, "Add");
        u.setTitle("Add Books");
        u.setVisible(true);
        jButtonEditBook.setEnabled(false);
        jButtonAddPhoto.setEnabled(false);
        setTable();
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonEditBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditBookActionPerformed
        lms.gui.dialog.JDialogEditBooks edit = new lms.gui.dialog.JDialogEditBooks(mainFrame, true, book, "Edit Books");
        edit.setVisible(true);
        setTable();
        jButtonEditBook.setEnabled(false);
        jButtonAddPhoto.setEnabled(false);
        edit.dispose();

    }//GEN-LAST:event_jButtonEditBookActionPerformed

    private void jButtonAddPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPhotoActionPerformed
        lms.gui.dialog.JDialogAddBookPhoto addPhoto = new JDialogAddBookPhoto(mainFrame, true, book);
        addPhoto.setVisible(true);
    }//GEN-LAST:event_jButtonAddPhotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAddPhoto;
    private javax.swing.JButton jButtonEditBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBook;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
     DefaultTableModel tableModel = new DefaultTableModel() {
        public Class getColumnClass(int columnIndex) {
            if (columnIndex == 0) {
                return String.class;
            }
            switch (columnIndex) {
                case 1:
                    return Integer.class;
                case 2:
                    return String.class;
                case 3:
                    return String.class;
                case 4:
                    return String.class;
                case 5:
                    return String.class;
                case 6:
                    return String.class;
                case 7:
                    return String.class;
                case 8:
                    return String.class;
                case 9:
                    return Integer.class;
                case 10:
                    return Integer.class;

                default:
                    return String.class;
            }
        }

        public boolean isCellEditable(int row, int col) {
            return false;
        }

    };

    private TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tableModel);

    public void setTable() {
        try {
            Vector<String> colname = new Vector<String>();
            colname.add("Id");
            colname.add("ISBN-13");
            colname.add("Title");//2
            colname.add("Author");//3
            colname.add("Publisher");//4
            colname.add("Description");//5
            colname.add("Notes");//6
            colname.add("Subjects");
            colname.add("URL");//8
            colname.add("QTY");//9
            colname.add("Price");
            colname.add("Genre");
            colname.add("Call No");
            colname.add("PriceNF");//13
            colname.add("PublisherId");//14
            colname.add("CallNoLineId");//15
            colname.add("GenreId");//16
            colname.add("CallKine2");//17
            colname.add("CallKine3");//18
            colname.add("CallKine4");//19

            ArrayList v1 = new QueryLMS().selectBooks();
            Vector vector = new Vector(v1);
            jTableBook = new JTable(tableModel);
            JTableHeader header = jTableBook.getTableHeader();
            header.setPreferredSize(new Dimension(100, 45));
            header.setFont(new Font("Courier New", Font.PLAIN, 14));
            header.setBackground(new java.awt.Color(153, 153, 153));
            jTableBook.setRowSorter(sorter);
            jTableBook.addMouseListener(this);
            jTableBook.setFont(new Font("Courier New", Font.PLAIN, 14));
            tableModel.setDataVector(vector, colname);
            jScrollPane1.setViewportView(jTableBook);

            TableColumn[] column = new TableColumn[100];
            column[0] = jTableBook.getColumnModel().getColumn(0);
            column[0].setPreferredWidth(0);
            column[1] = jTableBook.getColumnModel().getColumn(1);
            column[1].setPreferredWidth(100);
            column[2] = jTableBook.getColumnModel().getColumn(2);//title
            column[2].setPreferredWidth(300);
            column[2] = jTableBook.getColumnModel().getColumn(3);//
            column[2].setPreferredWidth(220);
            column[2] = jTableBook.getColumnModel().getColumn(3);
            column[2].setPreferredWidth(220);

            TableColumn hidden = jTableBook.getColumnModel().getColumn(0);
            hidden.setMinWidth(0);
            hidden.setPreferredWidth(0);
            hidden.setMaxWidth(0);
            TableColumn hidden1 = jTableBook.getColumnModel().getColumn(1);
            hidden1.setMinWidth(0);
            hidden1.setPreferredWidth(0);
            hidden1.setMaxWidth(0);

            TableColumn hidden2 = jTableBook.getColumnModel().getColumn(13);
            hidden2.setMinWidth(0);
            hidden2.setPreferredWidth(0);
            hidden2.setMaxWidth(0);
            TableColumn hidden3 = jTableBook.getColumnModel().getColumn(14);
            hidden3.setMinWidth(0);
            hidden3.setPreferredWidth(0);
            hidden3.setMaxWidth(0);
            TableColumn hidden4 = jTableBook.getColumnModel().getColumn(15);
            hidden4.setMinWidth(0);
            hidden4.setPreferredWidth(0);
            hidden4.setMaxWidth(0);
            TableColumn hidden5 = jTableBook.getColumnModel().getColumn(16);
            hidden5.setMinWidth(0);
            hidden5.setPreferredWidth(0);
            hidden5.setMaxWidth(0);
            TableColumn hidden6 = jTableBook.getColumnModel().getColumn(17);
            hidden6.setMinWidth(0);
            hidden6.setPreferredWidth(0);
            hidden6.setMaxWidth(0);
            TableColumn hidden7 = jTableBook.getColumnModel().getColumn(18);
            hidden7.setMinWidth(0);
            hidden7.setPreferredWidth(0);
            hidden7.setMaxWidth(0);
            TableColumn hidden8 = jTableBook.getColumnModel().getColumn(19);
            hidden8.setMinWidth(0);
            hidden8.setPreferredWidth(0);
            hidden8.setMaxWidth(0);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void mouseClicked(MouseEvent e) {
        if (e.getSource() == jTableBook) {
            if (e.getButton() == MouseEvent.BUTTON1) {
                if (e.getClickCount() == 1) {
                    jButtonEditBook.setEnabled(true);
                    jButtonAddPhoto.setEnabled(true);
                    int row = jTableBook.getSelectedRow();
                    if (row != -1) {
                        Object idl = jTableBook.getValueAt(row, 0);
                        Object isbnl = jTableBook.getValueAt(row, 1);
                        Object titlel = jTableBook.getValueAt(row, 2);
                        Object publisherl = jTableBook.getValueAt(row, 4);
                        Object descriptionl = jTableBook.getValueAt(row, 5);
                        Object notesl = jTableBook.getValueAt(row, 6);
                        Object subjectsl = jTableBook.getValueAt(row, 7);
                        Object urll = jTableBook.getValueAt(row, 8);
                        Object qtyl = jTableBook.getValueAt(row, 9);
                        Object pricel = jTableBook.getValueAt(row, 13);
                        Object publisherIdl = jTableBook.getValueAt(row, 14);
                        Object callNoLineId = jTableBook.getValueAt(row, 15);
                        Object genreIdl = jTableBook.getValueAt(row, 16);
                        Object CallNoLine2l = jTableBook.getValueAt(row, 17);
                        Object CallNoLine3l = jTableBook.getValueAt(row, 18);
                        Object CallNoLine4l = jTableBook.getValueAt(row, 19);

                        book.setId(Integer.parseInt(idl.toString()));
                        book.setIsbn(isbnl.toString());
                        book.setTitle(titlel.toString());
                        publisher.setId(Integer.parseInt(publisherIdl.toString()));
                        book.setPublisher(publisher);
                        book.setPrice(Float.parseFloat(pricel.toString()));
                        book.setDescription(descriptionl.toString());
                        book.setNotes(notesl.toString());
                        book.setSubjects(subjectsl.toString());
                        book.setUrl(urll.toString());
                        book.setQuantity(Integer.parseInt(qtyl.toString()));
                        callNoLine1.setId(Integer.parseInt(callNoLineId.toString()));
                        book.setCallNoLine1(callNoLine1);
                        genre.setId(Integer.parseInt(genreIdl.toString()));
                        book.setGenre(genre);
                        book.setCallNoLine2(CallNoLine2l.toString());
                        book.setCallNoLine3(CallNoLine3l.toString());
                        book.setCallNoLine4(CallNoLine4l.toString());

                        jButtonEditBook.setEnabled(true);
                        jButtonAddPhoto.setEnabled(true);

                    }

                }
            }

        }
    }

    public void mousePressed(MouseEvent e) {
    }

    public void mouseReleased(MouseEvent e) {
    }

    public void mouseEntered(MouseEvent e) {
    }

    public void mouseExited(MouseEvent e) {
    }

}
