/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms.reports;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JPanel;
import lms.util.DBConnection;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author admin
 */
public class JDialogBookInventory extends javax.swing.JDialog {
    private JPanel panel = new JPanel();
    private JasperPrint JPrint;
    private JRViewer jrviewer;
    /**
     * Creates new form JDialogPenaltyListReport
     */
    public JDialogBookInventory(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        BorderLayout layout = new BorderLayout();
        jDesktopPane1.setLayout(layout);
        BorderLayout layout1 = new BorderLayout();
        panel.setLayout(layout1);
        jDesktopPane1.add(panel, BorderLayout.CENTER);
        panel.setBounds(1, 2, 660, 500);
        jrviewer = new JRViewer(null);
        panel.add(jrviewer, BorderLayout.CENTER);
        jrviewer.setPreferredSize(new Dimension(600, 451));
        jrviewer.setAutoscrolls(true);
        showReport();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButtonPayPenalty = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1050, 550));

        jButtonPayPenalty.setMnemonic('R');
        jButtonPayPenalty.setText("<html><center>Print<br><p style=\"font-weight: bold; color: red;padding-top: 0px;\">Books</p></center></html>");
        jButtonPayPenalty.setFocusable(false);
        jButtonPayPenalty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPayPenaltyActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPayPenalty, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 97, -1));

        setSize(new java.awt.Dimension(1088, 657));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPayPenaltyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPayPenaltyActionPerformed

             JasperPrint JPrint;
        try {
            DBConnection con = new DBConnection();
            con.getDBConn();
            String fullPath = System.getProperty("user.dir") + "/src/lms/reports/books.jasper";
            Map<String, Object> param = new HashMap<String, Object>();
            JPrint = JasperFillManager.fillReport(fullPath, param, con.getCon());
            JasperPrintManager.printReport(JPrint, false); // print to default printer
            
            //JasperExportManager.exportReportToPdfFile(jp, "C:/Users/USER/Downloads/cor.pdf");

        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }//GEN-LAST:event_jButtonPayPenaltyActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPayPenalty;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
  public void showReport() {
        JasperPrint JPrint;
        try {
            DBConnection con = new DBConnection();
            con.getDBConn();
            String fullPath = System.getProperty("user.dir") + "/src/lms/reports/"
                    + "books.jasper";
            Map<String, Object> param = new HashMap<String, Object>();
            JPrint = JasperFillManager.fillReport(fullPath, param, con.getCon());
            JRViewer jrv = new JRViewer(JPrint);
            jDesktopPane1.removeAll();
            jDesktopPane1.add(jrv);
            jDesktopPane1.revalidate();
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }

}
