/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;
import javax.swing.JOptionPane;
import lms.gui.JFrameLogin;
import lms.util.DBConnection;

/**
 *
 * @author Java Programming with Aldrin
 */
public class JDialogDBConfiguration extends javax.swing.JDialog {

    /**
     * Creates new form JDialogDBConfiguration
     */
    private DBConnection dbconn = new DBConnection();
    private static String readFile = System.getProperty("user.dir") + "/src/lms/util/config.ini";

    public JDialogDBConfiguration(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jTextFieldDBDriver.setText(dbconn.getDbDriver());
        jTextFieldDatabase.setText(dbconn.getDatabase());
        jTextFieldJDBCUrl.setText(dbconn.getjDBCUr());
        jTextFieldServer.setText(dbconn.getServer());
        jTextFieldUsername.setText(dbconn.getUserID());
        jPasswordFieldPassword.setText(dbconn.getPassword());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldDBDriver = new javax.swing.JTextField();
        jTextFieldJDBCUrl = new javax.swing.JTextField();
        jTextFieldServer = new javax.swing.JTextField();
        jTextFieldDatabase = new javax.swing.JTextField();
        jTextFieldUsername = new javax.swing.JTextField();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Database Configuration");
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(400, 10));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel4.setPreferredSize(new java.awt.Dimension(400, 60));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 15));

        jButton1.setText("Test Connection");
        jButton1.setPreferredSize(new java.awt.Dimension(111, 30));
        jPanel4.add(jButton1);

        jButton2.setText("Save Connection");
        jButton2.setPreferredSize(new java.awt.Dimension(121, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);

        jPanel1.add(jPanel4, java.awt.BorderLayout.SOUTH);

        jPanel5.setPreferredSize(new java.awt.Dimension(10, 252));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.EAST);

        jPanel6.setPreferredSize(new java.awt.Dimension(10, 252));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.WEST);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(0, 1, 2, 2));

        jTextFieldDBDriver.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel2.add(jTextFieldDBDriver);

        jTextFieldJDBCUrl.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel2.add(jTextFieldJDBCUrl);

        jTextFieldServer.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel2.add(jTextFieldServer);

        jTextFieldDatabase.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel2.add(jTextFieldDatabase);

        jTextFieldUsername.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel2.add(jTextFieldUsername);
        jPanel2.add(jPasswordFieldPassword);

        jPanel7.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel8.setPreferredSize(new java.awt.Dimension(80, 432));
        jPanel8.setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("DB Driver");
        jPanel8.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("JDBC Url");
        jPanel8.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Server");
        jPanel8.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Database");
        jPanel8.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Username");
        jPanel8.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Password");
        jPanel8.add(jLabel6);

        jPanel7.add(jPanel8, java.awt.BorderLayout.WEST);

        jPanel1.add(jPanel7, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(418, 288));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Properties p = new Properties();
            p.setProperty("Server", this.jTextFieldServer.getText());
            p.setProperty("JDBCUrl", this.jTextFieldJDBCUrl.getText());
            p.setProperty("DBDriver", this.jTextFieldDBDriver.getText());
            p.setProperty("Database", jTextFieldDatabase.getText());
            p.setProperty("Password", this.jPasswordFieldPassword.getText());
            p.setProperty("UserID", jTextFieldUsername.getText());
            saveProperties(p, this.readFile);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldDBDriver;
    private javax.swing.JTextField jTextFieldDatabase;
    private javax.swing.JTextField jTextFieldJDBCUrl;
    private javax.swing.JTextField jTextFieldServer;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
   public void saveProperties(Properties p, String sFile) throws IOException {
        FileOutputStream out = null;
        try {
            out = new FileOutputStream(sFile);
            p.store(out, "");
            dbconn.getDBConn();
            if (dbconn.getCon() != null) {
                JOptionPane.showMessageDialog(this, "Connection successfully connected to database", "Connection Configuration", JOptionPane.PLAIN_MESSAGE);
                this.dispose();
            }
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Information", 0);
        } finally {
            try {
                out.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Information", 0);
            }
        }
    }
}
